# Generated by Django 5.0.7 on 2024-11-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopease', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
